:hammer: disable shellcheck

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -237,30 +237,30 @@ hadolint:
   script:
     - hadolint "Dockerfile"
 
-shellcheck:
-  <<: *preflight
-  image:
-    name: koalaman/shellcheck-alpine:stable
-    entrypoint: [""]
-  before_script:
-    - shellcheck --version
-    - apk --no-cache add grep
-    - |
-      find . -type f -print0 | \
-        xargs -0 sed -i 's:#!/usr/bin/with-contenv bash:#!/bin/bash:g'
-  script:
-    - |
-      for file in $(grep -IRl "#\!\(/usr/bin/env \|/bin/\)" --exclude-dir \
-        ".git" --exclude ".gitlab-ci.yml"); do
-        if ! shellcheck $file; then
-          export FAILED=1
-        else
-          echo "$file OK"
-        fi
-      done
-      if [ "${FAILED}" = "1" ]; then
-        exit 1
-      fi
+# shellcheck:
+#   <<: *preflight
+#   image:
+#     name: koalaman/shellcheck-alpine:stable
+#     entrypoint: [""]
+#   before_script:
+#     - shellcheck --version
+#     - apk --no-cache add grep
+#     - |
+#       find . -type f -print0 | \
+#         xargs -0 sed -i 's:#!/usr/bin/with-contenv bash:#!/bin/bash:g'
+#   script:
+#     - |
+#       for file in $(grep -IRl "#\!\(/usr/bin/env \|/bin/\)" --exclude-dir \
+#         ".git" --exclude ".gitlab-ci.yml"); do
+#         if ! shellcheck $file; then
+#           export FAILED=1
+#         else
+#           echo "$file OK"
+#         fi
+#       done
+#       if [ "${FAILED}" = "1" ]; then
+#         exit 1
+#       fi
 
 yamllint:
   <<: *preflight
